$(document).ready(function(){
                $("#guy").click(function(){
                    $("#popup1").fadeIn();
                });
                $("#popup1").click(function(){
                    $("#popup1").fadeOut();
                });
});
$(document).ready(function(){
                $("#chris").click(function(){
                    $("#popup2").fadeIn();
                });
                $("#popup2").click(function(){
                    $("#popup2").fadeOut();
                });
});
$(document).ready(function(){
                $("#will").click(function(){
                    $("#popup3").fadeIn();
                });
                $("#popup3").click(function(){
                    $("#popup3").fadeOut();
                });
});
$(document).ready(function(){
                $("#johny").click(function(){
                    $("#popup4").fadeIn();
                });
                $("#popup4").click(function(){
                    $("#popup4").fadeOut();
                });
});
});